// export const seasons = {
//   winter: {
//     closeProjects: 10,
//     income: 600000,
//     hired: 12,
//     dismissed: 19,
//     newProjects: 10,
//   },
//   spring: {
//     closeProjects: 10,
//     income: 750000,
//     hired: 15,
//     dismissed: 25,
//     newProjects: 10,
//   },
//   summer: {
//     closeProjects: 10,
//     income: 550000,
//     hired: 18,
//     dismissed: 11,
//     newProjects: 10,
//   },
//   autumn: {
//     closeProjects: 10,
//     income: 900000,
//     hired: 9,
//     dismissed: 12,
//     newProjects: 10,
//   },
// };

// export const hireds = [
//   {
//     name: "John",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Alice",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Michael",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Emma",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "David",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Sophia",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "James",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Olivia",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Daniel",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Emily",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "William",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Ava",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Alexander",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "Mia",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Benjamin",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "Charlotte",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Henry",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Elijah",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Scarlett",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Lucas",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Victoria",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
// ];

// export const dismissed = [
//   {
//     name: "John",
//     departament: "TECH",
//     workPeriod: 3,
//     salary: 400000,
//     isWill: false,
//   },
//   {
//     name: "Alice",
//     departament: "DESIGN",
//     workPeriod: 1,
//     salary: 250000,
//     isWill: true,
//   },
//   {
//     name: "Michael",
//     departament: "PROJECT",
//     workPeriod: 7,
//     salary: 800000,
//     isWill: false,
//   },
//   {
//     name: "Emma",
//     departament: "TECH",
//     workPeriod: 2,
//     salary: 350000,
//     isWill: false,
//   },
//   {
//     name: "David",
//     departament: "DESIGN",
//     workPeriod: 4,
//     salary: 500000,
//     isWill: true,
//   },
//   {
//     name: "Sophia",
//     departament: "PROJECT",
//     workPeriod: 5,
//     salary: 600000,
//     isWill: false,
//   },
//   {
//     name: "James",
//     departament: "TECH",
//     workPeriod: 0,
//     salary: 200000,
//     isWill: true,
//   },
//   {
//     name: "Olivia",
//     departament: "DESIGN",
//     workPeriod: 8,
//     salary: 900000,
//     isWill: false,
//   },
//   {
//     name: "Daniel",
//     departament: "PROJECT",
//     workPeriod: 6,
//     salary: 700000,
//     isWill: false,
//   },
//   {
//     name: "Emily",
//     departament: "TECH",
//     workPeriod: 3,
//     salary: 400000,
//     isWill: true,
//   },
//   {
//     name: "William",
//     departament: "DESIGN",
//     workPeriod: 1,
//     salary: 250000,
//     isWill: false,
//   },
//   {
//     name: "Ava",
//     departament: "PROJECT",
//     workPeriod: 7,
//     salary: 800000,
//     isWill: true,
//   },
//   {
//     name: "Alexander",
//     departament: "TECH",
//     workPeriod: 2,
//     salary: 350000,
//     isWill: true,
//   },
//   {
//     name: "Mia",
//     departament: "DESIGN",
//     workPeriod: 4,
//     salary: 500000,
//     isWill: false,
//   },
//   {
//     name: "Benjamin",
//     departament: "PROJECT",
//     workPeriod: 5,
//     salary: 600000,
//     isWill: true,
//   },
//   {
//     name: "Charlotte",
//     departament: "TECH",
//     workPeriod: 0,
//     salary: 200000,
//     isWill: false,
//   },
//   {
//     name: "Henry",
//     departament: "DESIGN",
//     workPeriod: 8,
//     salary: 900000,
//     isWill: true,
//   },
//   {
//     name: "Elijah",
//     departament: "PROJECT",
//     workPeriod: 6,
//     salary: 700000,
//     isWill: false,
//   },
//   {
//     name: "Scarlett",
//     departament: "TECH",
//     workPeriod: 3,
//     salary: 400000,
//     isWill: false,
//   },
//   {
//     name: "Lucas",
//     departament: "DESIGN",
//     workPeriod: 1,
//     salary: 250000,
//     isWill: true,
//   },
// ];
